info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T01:25:28.271Z"}
info: Connected to the database. {"timestamp":"2022-03-04T01:25:37.046Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T01:29:21.054Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T01:29:27.059Z"}
info: Connected to the database. {"timestamp":"2022-03-04T01:29:35.626Z"}
error: 
    status - 500 
    message - MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/
    at Function.Model.$wrapCallback (C:\taskOne\node_modules\mongoose\lib\model.js:5087:32)
    at C:\taskOne\node_modules\mongoose\lib\query.js:4510:21
    at promiseOrCallback (C:\taskOne\node_modules\mongoose\lib\helpers\promiseOrCallback.js:10:12)
    at model.Query.exec (C:\taskOne\node_modules\mongoose\lib\query.js:4509:10)
    at model.Query.Query.findOne (C:\taskOne\node_modules\mongoose\lib\query.js:2329:8)
    at model.Query.Query._findAndModify (C:\taskOne\node_modules\mongoose\lib\query.js:3642:16)
    at model.Query.<anonymous> (C:\taskOne\node_modules\mongoose\lib\query.js:3164:8)
    at model.Query._wrappedThunk [as _findOneAndUpdate] (C:\taskOne\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
    at C:\taskOne\node_modules\kareem\index.js:279:20
    at _next (C:\taskOne\node_modules\kareem\index.js:103:16)
    at C:\taskOne\node_modules\kareem\index.js:508:38
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/post/update/6220c61b9536922598872960 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T01:51:13.937Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T01:51:39.399Z"}
error: Could not connect to the database. querySrv ETIMEOUT _mongodb._tcp.demo.aoloa.mongodb.net {"code":"ETIMEOUT","hostname":"_mongodb._tcp.demo.aoloa.mongodb.net","stack":"Error: querySrv ETIMEOUT _mongodb._tcp.demo.aoloa.mongodb.net\n    at QueryReqWrap.onresolve [as oncomplete] (node:dns:213:19)","syscall":"querySrv","timestamp":"2022-03-04T01:52:55.045Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T01:58:05.361Z"}
info: Connected to the database. {"timestamp":"2022-03-04T01:58:14.496Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:06:16.958Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:06:26.177Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:09:06.684Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:09:14.618Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:09:23.145Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:09:59.022Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:10:07.594Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:10:56.358Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:11:05.525Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:12:53.966Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:13:00.287Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:13:08.973Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:16:59.649Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:17:08.025Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:17:43.132Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:17:51.586Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:18:38.623Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:18:47.254Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:21:56.686Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:22:05.970Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:22:12.468Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:22:20.788Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:22:41.244Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:22:49.489Z"}
error: 
      status - 2
      message - Cannot apply $pull to a non-array value 
      url - /api/v1/post/update/6220c61b9536922598872960 
      method - PUT 
      IP - ::ffff:127.0.0.1
     {"timestamp":"2022-03-04T02:22:54.353Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 2
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (C:\taskOne\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\taskOne\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\taskOne\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (C:\taskOne\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (C:\taskOne\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\taskOne\node_modules\express\lib\router\index.js:321:13)
    at C:\taskOne\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\taskOne\node_modules\express\lib\router\index.js:341:12)
    at Immediate.next (C:\taskOne\node_modules\express\lib\router\index.js:275:10)
    at Immediate._onImmediate (C:\taskOne\node_modules\express\lib\router\index.js:641:15)
    at processImmediate (node:internal/timers:466:21) 
    url - /api/v1/post/update/6220c61b9536922598872960 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T02:22:54.362Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:23:26.799Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:23:35.605Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:23:45.972Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:23:54.797Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:25:26.164Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:25:35.270Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:28:47.123Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:28:55.579Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:30:07.562Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:30:21.698Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:31:17.467Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:31:26.058Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:31:58.867Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:32:07.247Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:32:49.396Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:32:57.912Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:34:39.581Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:34:46.647Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:34:55.351Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:35:31.043Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:35:39.542Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:40:56.061Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:41:04.630Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T02:43:34.897Z"}
info: Connected to the database. {"timestamp":"2022-03-04T02:43:43.203Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:02:38.043Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:02:45.466Z"}
info: Connected to the database. {"timestamp":"2022-03-04T03:02:54.366Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'status')
    at _callee4$ (C:\taskOne\src\services\/user.service.js:55:7)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/post/update/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T03:02:58.851Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:04:48.687Z"}
info: Connected to the database. {"timestamp":"2022-03-04T03:04:57.553Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:05:32.035Z"}
info: Connected to the database. {"timestamp":"2022-03-04T03:05:40.822Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:05:47.531Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:05:53.058Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:05:59.907Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:06:10.396Z"}
info: Connected to the database. {"timestamp":"2022-03-04T03:06:18.822Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'status')
    at _callee4$ (C:\taskOne\src\services\/user.service.js:55:14)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/post/update/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T03:06:20.751Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:08:49.300Z"}
info: Connected to the database. {"timestamp":"2022-03-04T03:08:57.892Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'status')
    at _callee4$ (C:\taskOne\src\services\/user.service.js:56:14)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/post/update/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T03:09:01.764Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:09:22.495Z"}
info: Connected to the database. {"timestamp":"2022-03-04T03:09:32.358Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:10:21.233Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:10:35.563Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:10:42.709Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:10:56.174Z"}
info: Connected to the database. {"timestamp":"2022-03-04T03:11:06.859Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:11:35.428Z"}
info: Connected to the database. {"timestamp":"2022-03-04T03:11:43.965Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:12:20.229Z"}
info: Connected to the database. {"timestamp":"2022-03-04T03:12:28.737Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T03:30:41.515Z"}
info: Connected to the database. {"timestamp":"2022-03-04T03:30:50.187Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T04:48:27.556Z"}
info: Connected to the database. {"timestamp":"2022-03-04T04:48:36.538Z"}
error: 
    status - 500 
    message - TypeError: Cannot create property 'updatedAt' on number '36'
    at applyTimestampsToUpdate (C:\taskOne\node_modules\mongoose\lib\helpers\update\applyTimestampsToUpdate.js:74:31)
    at model.Query._setTimestampsOnUpdate (C:\taskOne\node_modules\mongoose\lib\helpers\timestamps\setupTimestamps.js:106:5)
    at callMiddlewareFunction (C:\taskOne\node_modules\kareem\index.js:483:23)
    at next (C:\taskOne\node_modules\kareem\index.js:58:7)
    at Kareem.execPre (C:\taskOne\node_modules\kareem\index.js:87:8)
    at Kareem.wrap (C:\taskOne\node_modules\kareem\index.js:266:8)
    at model.Query._updateOne (C:\taskOne\node_modules\kareem\index.js:376:11)
    at C:\taskOne\node_modules\mongoose\lib\query.js:4527:19
    at _next (C:\taskOne\node_modules\kareem\index.js:103:16)
    at C:\taskOne\node_modules\kareem\index.js:508:38
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/post/update/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T04:48:55.682Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T04:50:17.293Z"}
info: Connected to the database. {"timestamp":"2022-03-04T04:50:25.761Z"}
error: 
    status - 500 
    message - Error: Invalid atomic update value for $set. Expected an object, received number
    at castUpdate (C:\taskOne\node_modules\mongoose\lib\helpers\query\castUpdate.js:102:13)
    at model.Query._castUpdate (C:\taskOne\node_modules\mongoose\lib\query.js:4721:10)
    at castDoc (C:\taskOne\node_modules\mongoose\lib\query.js:4751:18)
    at model.Query._updateThunk (C:\taskOne\node_modules\mongoose\lib\query.js:3877:20)
    at model.Query.<anonymous> (C:\taskOne\node_modules\mongoose\lib\query.js:3979:23)
    at model.Query._wrappedThunk [as _updateOne] (C:\taskOne\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
    at C:\taskOne\node_modules\kareem\index.js:370:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
    url - /api/v1/post/update/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T04:50:28.080Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T04:52:18.743Z"}
info: Connected to the database. {"timestamp":"2022-03-04T04:52:27.415Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T04:56:56.531Z"}
info: Connected to the database. {"timestamp":"2022-03-04T04:56:59.623Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:06:43.798Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:06:52.548Z"}
error: 
    status - 500 
    message - ReferenceError: likes is not defined
    at _callee4$ (C:\taskOne\src\services\/user.service.js:54:14)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/post/update/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T05:07:04.710Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:08:39.987Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:08:48.586Z"}
error: 
    status - 500 
    message - TypeError: post.updateOne is not a function
    at _callee4$ (C:\taskOne\src\services\/user.service.js:52:14)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/post/update/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T05:09:00.252Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:09:36.692Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:09:45.666Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:12:08.447Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:12:17.137Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:13:12.335Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:13:20.846Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:15:15.902Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:15:24.309Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:16:27.389Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:16:35.842Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:17:38.943Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:17:47.232Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:18:05.005Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:18:13.180Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:21:54.779Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:22:03.728Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:22:31.706Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:22:40.139Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:25:21.796Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:25:30.079Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:25:59.699Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:26:07.980Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to find() must be an object, got 62217c7628629f352c170f07
    at model.Query.Query.find (C:\taskOne\node_modules\mongoose\lib\query.js:2098:16)
    at Function.find (C:\taskOne\node_modules\mongoose\lib\model.js:2157:13)
    at _callee4$ (C:\taskOne\src\services\/user.service.js:50:30)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.upadtePost (C:\taskOne\src\services\/user.service.js:49:24)
    at _callee4$ (C:\taskOne\src\controllers\/user.controller.js:52:36)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21) 
    url - /api/v1/post/update/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T05:26:09.960Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:26:53.525Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:27:01.719Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:28:15.638Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:28:24.278Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:28:48.836Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:28:56.952Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:30:10.452Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:30:18.816Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:31:26.800Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:31:35.203Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:32:22.886Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:32:31.148Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:33:17.623Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:33:25.943Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:48:37.274Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:48:47.138Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading '_id')
    at _callee4$ (C:\taskOne\src\services\/user.service.js:51:56)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.likePost (C:\taskOne\src\services\/user.service.js:50:22)
    at _callee3$ (C:\taskOne\src\controllers\/user.controller.js:38:36)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/post/like/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T05:48:48.002Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:50:44.526Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:50:53.608Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading '_id')
    at _callee4$ (C:\taskOne\src\services\/user.service.js:51:56)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.likePost (C:\taskOne\src\services\/user.service.js:50:22)
    at _callee3$ (C:\taskOne\src\controllers\/user.controller.js:38:36)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/post/like/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T05:51:01.760Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:52:46.605Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:52:56.252Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading '_id')
    at _callee4$ (C:\taskOne\src\services\/user.service.js:51:56)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.likePost (C:\taskOne\src\services\/user.service.js:50:22)
    at _callee3$ (C:\taskOne\src\controllers\/user.controller.js:38:36)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/post/like/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T05:52:58.852Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:53:51.688Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:54:04.889Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:54:13.455Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'id')
    at _callee4$ (C:\taskOne\src\services\/user.service.js:51:56)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.likePost (C:\taskOne\src\services\/user.service.js:50:22)
    at _callee3$ (C:\taskOne\src\controllers\/user.controller.js:38:36)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/post/like/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T05:54:14.284Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:54:51.161Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:54:59.938Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T05:55:38.349Z"}
info: Connected to the database. {"timestamp":"2022-03-04T05:55:48.377Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading '_id')
    at _callee4$ (C:\taskOne\src\services\/user.service.js:51:56)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.likePost (C:\taskOne\src\services\/user.service.js:50:22)
    at _callee3$ (C:\taskOne\src\controllers\/user.controller.js:38:36)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/post/like/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T05:56:21.228Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T06:00:22.574Z"}
info: Connected to the database. {"timestamp":"2022-03-04T06:00:30.970Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T06:00:48.208Z"}
info: Connected to the database. {"timestamp":"2022-03-04T06:00:56.725Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T06:24:36.786Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T06:26:17.815Z"}
info: Connected to the database. {"timestamp":"2022-03-04T06:26:28.552Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T06:31:36.225Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T06:34:28.639Z"}
info: Connected to the database. {"timestamp":"2022-03-04T06:34:38.476Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T06:36:39.908Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T06:36:51.030Z"}
info: Connected to the database. {"timestamp":"2022-03-04T06:36:59.479Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T06:57:06.497Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T06:57:27.331Z"}
info: Connected to the database. {"timestamp":"2022-03-04T06:57:35.804Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T06:59:24.187Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T06:59:43.965Z"}
info: Connected to the database. {"timestamp":"2022-03-04T06:59:53.439Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:00:01.851Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:00:41.678Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:01:12.011Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:01:20.089Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:01:46.247Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:01:54.399Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:03:34.305Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:03:58.967Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:04:07.787Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:06:16.701Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:06:26.340Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:06:43.812Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:06:52.324Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:06:59.669Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:07:09.129Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:07:19.229Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:07:27.794Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:07:34.788Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:07:43.207Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:08:07.629Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:08:18.775Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:08:30.784Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:08:37.035Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:08:45.605Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:09:00.501Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:09:08.952Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading '_id')
    at _callee5$ (C:\taskOne\src\services\/user.service.js:68:64)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.commentPost (C:\taskOne\src\services\/user.service.js:67:25)
    at _callee4$ (C:\taskOne\src\controllers\/user.controller.js:76:36)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/post/comment/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T07:09:54.755Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:10:16.608Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:10:25.112Z"}
error: 
    status - 500 
    message - ReferenceError: commentobj is not defined
    at _callee5$ (C:\taskOne\src\services\/user.service.js:69:13)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/post/comment/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T07:10:26.511Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:11:35.372Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:11:41.515Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:11:49.935Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:12:11.371Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:12:22.190Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:12:31.441Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:12:39.743Z"}
error: 
    status - 500 
    message - ReferenceError: commentobj is not defined
    at _callee5$ (C:\taskOne\src\services\/user.service.js:69:13)
    at tryCatch (C:\taskOne\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\taskOne\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\taskOne\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\taskOne\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/post/comment/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T07:12:51.380Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:13:40.324Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:13:48.642Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:16:14.724Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:16:26.530Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:16:31.106Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:16:39.519Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:17:57.706Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:18:06.605Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:18:19.201Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:18:27.992Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:19:11.357Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:19:20.138Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:19:29.439Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:28:58.212Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:29:06.607Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:30:29.135Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:30:43.119Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:30:51.628Z"}
error: 
    status - 500 
    message - CastError: Cast to [string] failed for value "[{}]" (type string) at path "comments.0"
    at model.Query.exec (C:\taskOne\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\taskOne\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/post/comment/62217c7628629f352c170f07 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-03-04T07:30:59.238Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:31:31.924Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:31:44.881Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:31:50.740Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:31:59.201Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T07:33:06.997Z"}
info: Connected to the database. {"timestamp":"2022-03-04T07:33:15.247Z"}
info: Server started at http://localhost:3060/api/v1/ {"timestamp":"2022-03-04T08:27:26.147Z"}
info: Connected to the database. {"timestamp":"2022-03-04T08:27:35.247Z"}
